main google page tests added
RedRoverSchool/JenkinsQA_2024_fall pull request #59
Opened 2024-10-18 21:58 UTC by ihor-voloshyn

main google page tests added

2024-10-18 22:04 UTC, NataliaKalugina approved these changes

2024-10-18 22:21 UTC, ArtsiomAzaranka approved these changes

2024-10-18 22:22 UTC, tereshenkov29 requested changes

2024-10-18 22:22 UTC, tereshenkov29 commented on pom.xml
> +        <dependency>
внесение изменений в проектный pom согласованы с Сергеем?

2024-10-18 22:24 UTC, ihor-voloshyn commented on pom.xml
> +        <dependency>
не согласовывал, но без этих зависимостей останутся ошибки по логам и у меня не запустятся тесты

2024-10-18 22:25 UTC, ihor-voloshyn commented on pom.xml
> +        <dependency>
отравлю на согласование Сергею

2024-10-19 03:28 UTC, SergeiDemyanenko commented on pom.xml
> +        </dependency>
Зачем это тут?

2024-10-19 07:00 UTC, ihor-voloshyn commented on pom.xml
> +        </dependency>
Для следующих тестов, я удалил несколько тестов из коммита поскольку не работали, сделаю фикс и добавлю тесты в следующий коммит.

2024-10-19 10:22 UTC, closed without merging